version: '3'

services:
  shlink-interface:
    container_name: shlink-interface
    build:
      context: .
      args:
        - PROXY_URL
    networks:
      - proxy-manager

networks:
  proxy-manager:
    name: proxy-manager-shlink
    external: true
